### ISSUE TITLE
Behavior Driven Development - typo

### ISSUE THREAD

**Issue by Iuhegi** [devopsdojoconsortium/dojoconsortium.org#22]
In first example
`the the` [->](https://github.com/devopsdojoconsortium/dojoconsortium.org/blob/main/content/en/docs/work-decomposition/behavior-driven-development.md?plain=1#L22) `the`

In Using Acceptance Criteria to Negotiate and Split
`First we` [->](https://github.com/devopsdojoconsortium/dojoconsortium.org/blob/main/content/en/docs/work-decomposition/behavior-driven-development.md?plain=1#L72) `First, we`

**Comment by seanpoulter** [comment]
Would you welcome a PR to fix all the `the the`s, and possible all the repeated/stuttered words?

**Comment by Iuhegi** [comment]
Fixed in #28
