### ISSUE TITLE
Broken link on Work Decomposition

### ISSUE THREAD

**Issue by seanpoulter** [devopsdojoconsortium/dojoconsortium.org#29]
## Problem

Given I am on https://dojoconsortium.org/docs/work-decomposition/complexity-workbreakdown
When I click on the link with the text **[Stories are too complex](https://dojoconsortium.org/docs/work-decomposition/complexity-workbreakdown)**
Then I navigate to a page with 404 Not Found

## Proposed solution

Should this be a link to: https://dojoconsortium.org/docs/work-decomposition/complexity-and-estimation/?

**Comment by bdfinst** [comment]
Fixed
