### ISSUE TITLE
Embedded code in Testing Best Practices and More

### ISSUE THREAD

**Issue by seanpoulter** [devopsdojoconsortium/dojoconsortium.org#30]
## Problem

The following pages do not embed the referenced code:

* https://dojoconsortium.org/testing/best-practices/#naming-conventions
* https://dojoconsortium.org/testing/unit/#examples
* https://dojoconsortium.org/testing/unit/#examples

The code samples render like:

> `embed:examples/naming-convention.js` `embed:examples/naming-convention.java`

**Comment by bdfinst** [comment]
Fixed
