### ISSUE TITLE
starting-ci-cd has dead link to improvement-kata

### ISSUE THREAD

**Issue by jasonpatrickellykrause** [devopsdojoconsortium/dojoconsortium.org#32]
Getting Started\Recommended Practices contains a link to `improvement kata` which appears to be a draft in the old content. 

https://dojoconsortium.org/docs/starting-ci-cd/#recommended-practices

https://github.com/devopsdojoconsortium/dojoconsortium.org/blob/main/content-old/drafts/playbooks/improvement-kata.md

Should we remove link or update an publish kata?

**Comment by bdfinst** [comment]
Fixed
