### ISSUE TITLE
Spelling in meta tags on main site

### ISSUE THREAD

**Issue by nigelatdas** [devopsdojoconsortium/dojoconsortium.org#7]
Hi all, 
I would have raised as PR and fixed it.. but it's in the main site, not this repo. 

https://dojoconsortium.org/
![image](https://user-images.githubusercontent.com/91711992/192396487-ba2a900c-e6d2-4258-b690-ca9ec628f685.png)

We should probably use the traditional spelling of Production :)

**Comment by bdfinst** [comment]
Dunno, seems boring.

**Comment by bdfinst** [comment]
Fixed it.
