### ISSUE TITLE
Missing Testing Strategy ADR

### ISSUE THREAD

**Issue by aaronzhongg** [devopsdojoconsortium/dojoconsortium.org#9]
https://github.com/devopsdojoconsortium/dojoconsortium.org/blob/main/content/en/Testing/best-practices.md has a link to the Testing Strategy ADR but is not found 

ADR link: https://github.com/devopsdojoconsortium/dojoconsortium.org/blob/main/adrs/001

**Comment by bdfinst** [comment]
Link should have been removed. Done.
